using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using HarmonyLib;
using RimWorld;
using RimWorld.Planet;
using RimWorld.QuestGen;
using UnityEngine;
using Verse;

namespace DeferredRaidGeneration
{
    /// <summary>
    /// A Beggars or Hospitality_Refugee quest. Both generate their whole group (colony population x 0.25-0.75, plus
    /// generated relatives) inside QuestGen.Generate in one frame. The group size, child count and the temporary
    /// faction are decided first; the pawns are generated over several seconds; then the vanilla quest is generated
    /// with those decisions and pawns handed back to it.
    /// </summary>
    public class PendingQuest : PendingGeneration
    {
        public QuestScriptDef Def;
        public Map Map;
        public Faction Faction;
        public PawnKindDef Kind;
        public int LodgerCount;
        public int ChildCount;
        /// <summary>Seed of the random state the quest rolls its child count with, so planning and replay agree.</summary>
        public int Seed;
        /// <summary>The original call that generates the quest.</summary>
        public Action Run;

        internal bool RandPushed;
        internal bool FactionHandedOver;
        internal int HandedOver;

        public override int Count => LodgerCount;
        public override string Label => Def.defName;
        public override bool StillValid => Find.Maps.Contains(Map) && Map.IsPlayerHome;

        public bool IsBeggars => Def.defName == DeferredQuests.Beggars;

        /// <summary>Same order as the quest roots: children are the last ChildCount pawns; a refugee leader is never one.</summary>
        public DevelopmentalStage StageOf(int index)
        {
            bool child = IsBeggars ? index >= LodgerCount - ChildCount : index > 0 && index >= LodgerCount - ChildCount;
            return child ? DevelopmentalStage.Child : DevelopmentalStage.Adult;
        }

        /// <summary>Same requests QuestNode_Root_Beggars and QuestNode_Root_Hospitality_Refugee build.</summary>
        protected override Pawn GeneratePawn(int index)
        {
            DevelopmentalStage stage = StageOf(index);
            PawnGenerationRequest request;
            if (IsBeggars)
            {
                request = new PawnGenerationRequest(Kind, Faction, PawnGenerationContext.NonPlayer, Map.Tile, forceGenerateNewPawn: true,
                    allowDead: false, allowDowned: false, canGeneratePawnRelations: true, mustBeCapableOfViolence: false, 1f,
                    forceAddFreeWarmLayerIfNeeded: false, allowGay: true, allowPregnant: true, allowFood: true, allowAddictions: true,
                    inhabitant: false, certainlyBeenInCryptosleep: false, forceRedressWorldPawnIfFormerColonist: false,
                    worldPawnFactionDoesntMatter: false, 0f, 0f, null, 1f, null, null, null, null, null, null, null, null, null, null,
                    null, null, forceNoIdeo: false, forceNoBackstory: false, forbidAnyTitle: false, forceDead: false, null, null, null,
                    null, null, 0f, stage);
            }
            else
            {
                request = new PawnGenerationRequest(Kind, Faction, PawnGenerationContext.NonPlayer, Map.Tile, forceGenerateNewPawn: true,
                    allowDead: false, allowDowned: false, canGeneratePawnRelations: true, mustBeCapableOfViolence: true, 1f,
                    forceAddFreeWarmLayerIfNeeded: false, allowGay: true, allowPregnant: true, allowFood: true, allowAddictions: true,
                    inhabitant: false, certainlyBeenInCryptosleep: false, forceRedressWorldPawnIfFormerColonist: false,
                    worldPawnFactionDoesntMatter: false, 0f, 0f, null, 0f, null, null, null, null, null, null, null, null, null, null,
                    null, null, forceNoIdeo: false, forceNoBackstory: false, forbidAnyTitle: false, forceDead: false, null, null, null,
                    null, null, 0f, stage);
                request.BiocodeApparelChance = 0f;
            }
            return PawnGenerator.GeneratePawn(request);
        }

        public override void Execute()
        {
            DeferredQuests.Replaying = this;
            try
            {
                Run();
            }
            finally
            {
                if (RandPushed)
                    Rand.PopState();
                RandPushed = false;
                DeferredQuests.Replaying = null;
            }
        }
    }

    public static class DeferredQuests
    {
        public const string Beggars = "Beggars";
        public const string Refugee = "Hospitality_Refugee";

        /// <summary>Set while a finished quest is being generated by the vanilla quest code.</summary>
        public static PendingQuest Replaying;

        public static bool Supported(QuestScriptDef def)
        {
            if (def == null)
                return false;
            return def.defName == Beggars && ModsConfig.IdeologyActive || def.defName == Refugee && ModsConfig.RoyaltyActive;
        }

        /// <summary>
        /// Plans the quest as its root node would up to pawn generation and queues it. Returns false to let vanilla
        /// generate it immediately. population is the slate override (0 = the map's colonists, as vanilla).
        /// </summary>
        public static bool TryDefer(QuestScriptDef def, Map map, int population, Action run)
        {
            DeferredRaids component = DeferredRaids.Instance;
            if (component == null || DeferredRaids.Disabled || DeferredRaids.AnyReplaying || !Supported(def) || map == null)
                return false;

            var slate = new Slate();
            if (population > 0)
                slate.Set("population", population);
            int lodgerCount = QuestNode_Root_Beggars.LodgerCountFromPopulation(slate, map);
            if (lodgerCount < DeferredRaids.MinPawnsToDefer)
                return false;

            bool beggars = def.defName == Beggars;
            int seed = Rand.Int;
            int childCount = RollChildCount(beggars, lodgerCount, seed);
            var quest = new PendingQuest
            {
                Def = def,
                Map = map,
                Faction = beggars ? NewBeggarFaction() : NewRefugeeFaction(),
                Kind = beggars ? PawnKindDefOf.Beggar : PawnKindDefOf.Refugee,
                LodgerCount = lodgerCount,
                ChildCount = childCount,
                Seed = seed,
                Run = run,
            };
            component.Enqueue(quest);
            if (Prefs.DevMode)
                Log.Message($"[DeferredRaidGeneration] Deferred quest {def.defName}: {lodgerCount} pawns ({childCount} children).");
            Patch_MapPawns_AllPawnsUnspawned.ResetStats();
            return true;
        }

        /// <summary>
        /// The child-count roll of each quest root. The replay runs the root's own roll from the same seed (pushed when
        /// the root asks for the lodger count), which gives the same result as long as nothing else draws random
        /// numbers in between; if it differs anyway, pawns of the other stage are generated normally.
        /// </summary>
        private static int RollChildCount(bool beggars, int lodgerCount, int seed)
        {
            if (!Find.Storyteller.difficulty.ChildrenAllowed || !beggars && lodgerCount < 2)
                return 0;
            Rand.PushState(seed);
            try
            {
                (int, float) result;
                if (beggars)
                {
                    new List<(int, float)>
                    {
                        (0, 0.4f),
                        (Rand.Range(1, Mathf.Max(1, lodgerCount / 2)), 0.4f),
                        (lodgerCount, 0.2f)
                    }.TryRandomElementByWeight(((int, float) p) => p.Item2, out result);
                }
                else
                {
                    new List<(int, float)>
                    {
                        (0, 0.7f),
                        (Rand.Range(1, lodgerCount / 2), 0.2f),
                        (lodgerCount - 1, 0.1f)
                    }.TryRandomElementByWeight(((int, float) p) => p.Item2, out result);
                }
                return result.Item1;
            }
            finally
            {
                Rand.PopState();
            }
        }

        private static List<FactionRelation> NeutralRelations(FactionDef def)
        {
            var list = new List<FactionRelation>();
            foreach (Faction item in Find.FactionManager.AllFactionsListForReading)
            {
                if (!item.def.PermanentlyHostileTo(def))
                    list.Add(new FactionRelation { other = item, kind = FactionRelationKind.Neutral });
            }
            return list;
        }

        private static Faction NewBeggarFaction()
        {
            Faction faction = FactionGenerator.NewGeneratedFactionWithRelations(FactionDefOf.Beggars, NeutralRelations(FactionDefOf.Beggars), hidden: true);
            faction.temporary = true;
            Find.FactionManager.Add(faction);
            return faction;
        }

        private static Faction NewRefugeeFaction()
        {
            FactionDef def = FactionDefOf.OutlanderRefugee;
            bool? hidden = true;
            var parms = new FactionGeneratorParms(def, default(IdeoGenerationParms), hidden);
            if (ModsConfig.IdeologyActive)
                parms.ideoGenerationParms = new IdeoGenerationParms(parms.factionDef, forceNoExpansionIdeo: false,
                    DefDatabase<PreceptDef>.AllDefs.Where(p => p.proselytizes || p.approvesOfCharity).ToList());
            Faction faction = FactionGenerator.NewGeneratedFactionWithRelations(parms, NeutralRelations(def));
            faction.temporary = true;
            Find.FactionManager.Add(faction);
            return faction;
        }
    }

    /// <summary>Storyteller quests (GiveQuest_Beggars, random quests) are deferred here and replayed through the same call.</summary>
    [HarmonyPatch(typeof(IncidentWorker_GiveQuest), "GiveQuest")]
    public static class Patch_IncidentWorker_GiveQuest_GiveQuest
    {
        private static readonly MethodInfo GiveQuest = AccessTools.Method(typeof(IncidentWorker_GiveQuest), "GiveQuest");

        public static bool Prefix(IncidentWorker_GiveQuest __instance, IncidentParms parms, QuestScriptDef questDef)
        {
            if (!DeferredQuests.Supported(questDef) || DeferredRaids.AnyReplaying)
                return true;
            try
            {
                Map map = QuestGen_Get.GetMap();
                return !DeferredQuests.TryDefer(questDef, map, 0, () => GiveQuest.Invoke(__instance, new object[] { parms, questDef }));
            }
            catch (Exception e)
            {
                Log.Error("[DeferredRaidGeneration] Could not defer quest, generating it normally: " + e);
                return true;
            }
        }
    }

    /// <summary>During a replay the root gets the planned lodger count, and the planned seed for its child roll.</summary>
    [HarmonyPatch(typeof(QuestNode_Root_Beggars), nameof(QuestNode_Root_Beggars.LodgerCountFromPopulation))]
    public static class Patch_QuestNode_Root_Beggars_LodgerCountFromPopulation
    {
        public static bool Prefix(ref int __result)
        {
            PendingQuest quest = DeferredQuests.Replaying;
            if (quest == null || !QuestGen.Working)
                return true;
            __result = quest.LodgerCount;
            if (!quest.RandPushed)
            {
                Rand.PushState(quest.Seed);
                quest.RandPushed = true;
            }
            return false;
        }
    }

    /// <summary>During a replay the root gets the faction created when the quest was planned.</summary>
    [HarmonyPatch(typeof(FactionGenerator), nameof(FactionGenerator.NewGeneratedFactionWithRelations),
        typeof(PlanetLayer), typeof(FactionGeneratorParms), typeof(List<FactionRelation>))]
    public static class Patch_FactionGenerator_NewGeneratedFactionWithRelations
    {
        public static bool Prefix(FactionGeneratorParms parms, ref Faction __result)
        {
            PendingQuest quest = DeferredQuests.Replaying;
            if (quest == null || quest.FactionHandedOver || parms.factionDef != quest.Faction.def)
                return true;
            quest.FactionHandedOver = true;
            __result = quest.Faction;
            return false;
        }
    }

    /// <summary>During a replay the quest goes to the map it was planned for.</summary>
    [HarmonyPatch(typeof(QuestGen_Get), nameof(QuestGen_Get.GetMap))]
    public static class Patch_QuestGen_Get_GetMap
    {
        public static bool Prefix(ref Map __result)
        {
            PendingQuest quest = DeferredQuests.Replaying;
            if (quest == null || !Find.Maps.Contains(quest.Map))
                return true;
            __result = quest.Map;
            return false;
        }
    }

    /// <summary>During a replay the root's pawn requests take the matching pre-generated pawns.</summary>
    [HarmonyPatch(typeof(PawnGenerator), nameof(PawnGenerator.GeneratePawn), typeof(PawnGenerationRequest))]
    public static class Patch_PawnGenerator_GeneratePawn_QuestReplay
    {
        [HarmonyPriority(Priority.First)]
        public static bool Prefix(PawnGenerationRequest request, ref Pawn __result)
        {
            PendingQuest quest = DeferredQuests.Replaying;
            if (quest == null)
                return true;
            // The child roll is done once the root starts generating its pawns.
            if (quest.RandPushed)
            {
                Rand.PopState();
                quest.RandPushed = false;
            }
            if (request.KindDef != quest.Kind || request.Faction != quest.Faction)
                return true;
            int index = quest.Generated.FindIndex(p => !p.Destroyed && request.AllowedDevelopmentalStages.Has(p.DevelopmentalStage));
            if (index < 0)
                return true;
            __result = quest.Generated[index];
            quest.Generated.RemoveAt(index);
            quest.HandedOver++;
            return false;
        }
    }

    /// <summary>
    /// A quest group that arrives later (refugees arrive when the quest is accepted) gets the same arrival treatment
    /// as a replayed group: the died-thoughts shortcut while spawning, and first job searches spread over a few ticks.
    /// </summary>
    [HarmonyPatch(typeof(QuestPart_PawnsArrive), nameof(QuestPart_PawnsArrive.Notify_QuestSignalReceived))]
    public static class Patch_QuestPart_PawnsArrive_Group
    {
        [HarmonyPriority(Priority.First)]
        public static void Prefix(QuestPart_PawnsArrive __instance, Signal signal, out bool __state)
        {
            __state = !DeferredRaids.Disabled && DeferredRaids.ReplayPawns == null && signal.tag == __instance.inSignal
                && __instance.pawns.Count >= DeferredRaids.MinPawnsToDefer;
            if (!__state)
                return;
            DeferredRaids.ReplayPawns = new HashSet<Pawn>(__instance.pawns);
            DeferredRaids.DiedThoughtHolders = null;
            DeferredRaids.Staggered.Clear();
        }

        public static Exception Finalizer(Exception __exception, QuestPart_PawnsArrive __instance, bool __state)
        {
            if (!__state)
                return __exception;
            try
            {
                // Arriving pawns without a lord pick their first job on their first tick, all in the same tick.
                foreach (Pawn pawn in __instance.pawns)
                {
                    if (!DeferredRaids.Staggered.Contains(pawn))
                        DeferredRaids.Staggered.Add(pawn);
                }
                DeferredRaids.StartStaggeredWaits();
            }
            finally
            {
                DeferredRaids.ReplayPawns = null;
                DeferredRaids.DiedThoughtHolders = null;
                DeferredRaids.Staggered.Clear();
            }
            return __exception;
        }
    }
}
