using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using HarmonyLib;
using RimWorld;
using RimWorld.Planet;
using RimWorld.QuestGen;
using UnityEngine;
using Verse;
using Verse.AI;

namespace DeferredRaidGeneration
{
    /// <summary>
    /// A Beggars or Hospitality_Refugee quest. Both generate their whole group (colony population x 0.25-0.75, plus
    /// generated relatives) inside QuestGen.Generate in one frame. The group size, child count and the temporary
    /// faction are decided first; the pawns are generated over several seconds; then the vanilla quest is generated
    /// with those decisions and pawns handed back to it.
    /// </summary>
    public class PendingQuest : PendingGeneration
    {
        public QuestScriptDef Def;
        public Map Map;
        public Faction Faction;
        public PawnKindDef Kind;
        public int LodgerCount;
        public int ChildCount;
        /// <summary>Seed of the random state the quest rolls its child count with, so planning and replay agree.</summary>
        public int Seed;
        /// <summary>The original call that generates the quest.</summary>
        public Action Run;

        internal bool RandPushed;
        internal bool FactionHandedOver;
        internal int HandedOver;

        public override int Count => LodgerCount;
        public override string Label => Def.defName;
        public override bool StillValid => Find.Maps.Contains(Map) && Map.IsPlayerHome;

        public bool IsBeggars => Def.defName == DeferredQuests.Beggars;

        /// <summary>Same order as the quest roots: children are the last ChildCount pawns; a refugee leader is never one.</summary>
        public DevelopmentalStage StageOf(int index)
        {
            bool child = IsBeggars ? index >= LodgerCount - ChildCount : index > 0 && index >= LodgerCount - ChildCount;
            return child ? DevelopmentalStage.Child : DevelopmentalStage.Adult;
        }

        /// <summary>Same requests QuestNode_Root_Beggars and QuestNode_Root_Hospitality_Refugee build.</summary>
        protected override Pawn GeneratePawn(int index)
        {
            DevelopmentalStage stage = StageOf(index);
            PawnGenerationRequest request;
            if (IsBeggars)
            {
                request = new PawnGenerationRequest(Kind, Faction, PawnGenerationContext.NonPlayer, Map.Tile, forceGenerateNewPawn: true,
                    allowDead: false, allowDowned: false, canGeneratePawnRelations: true, mustBeCapableOfViolence: false, 1f,
                    forceAddFreeWarmLayerIfNeeded: false, allowGay: true, allowPregnant: true, allowFood: true, allowAddictions: true,
                    inhabitant: false, certainlyBeenInCryptosleep: false, forceRedressWorldPawnIfFormerColonist: false,
                    worldPawnFactionDoesntMatter: false, 0f, 0f, null, 1f, null, null, null, null, null, null, null, null, null, null,
                    null, null, forceNoIdeo: false, forceNoBackstory: false, forbidAnyTitle: false, forceDead: false, null, null, null,
                    null, null, 0f, stage);
            }
            else
            {
                request = new PawnGenerationRequest(Kind, Faction, PawnGenerationContext.NonPlayer, Map.Tile, forceGenerateNewPawn: true,
                    allowDead: false, allowDowned: false, canGeneratePawnRelations: true, mustBeCapableOfViolence: true, 1f,
                    forceAddFreeWarmLayerIfNeeded: false, allowGay: true, allowPregnant: true, allowFood: true, allowAddictions: true,
                    inhabitant: false, certainlyBeenInCryptosleep: false, forceRedressWorldPawnIfFormerColonist: false,
                    worldPawnFactionDoesntMatter: false, 0f, 0f, null, 0f, null, null, null, null, null, null, null, null, null, null,
                    null, null, forceNoIdeo: false, forceNoBackstory: false, forbidAnyTitle: false, forceDead: false, null, null, null,
                    null, null, 0f, stage);
                request.BiocodeApparelChance = 0f;
            }
            return PawnGenerator.GeneratePawn(request);
        }

        public override void Execute()
        {
            DeferredQuests.Replaying = this;
            try
            {
                Run();
            }
            finally
            {
                if (RandPushed)
                    Rand.PopState();
                RandPushed = false;
                DeferredQuests.Replaying = null;
            }
        }
    }

    public static class DeferredQuests
    {
        public const string Beggars = "Beggars";
        public const string Refugee = "Hospitality_Refugee";

        /// <summary>Set while a finished quest is being generated by the vanilla quest code.</summary>
        public static PendingQuest Replaying;

        public static bool Supported(QuestScriptDef def)
        {
            if (def == null)
                return false;
            return def.defName == Beggars && ModsConfig.IdeologyActive || def.defName == Refugee && ModsConfig.RoyaltyActive;
        }

        /// <summary>
        /// Plans the quest as its root node would up to pawn generation and queues it. Returns false to let vanilla
        /// generate it immediately. population is the slate override (0 = the map's colonists, as vanilla).
        /// </summary>
        public static bool TryDefer(QuestScriptDef def, Map map, int population, Action run)
        {
            DeferredRaids component = DeferredRaids.Instance;
            if (component == null || !Features.QuestDeferralActive || DeferredRaids.Disabled || DeferredRaids.AnyReplaying || !Supported(def) || map == null)
                return false;

            var slate = new Slate();
            if (population > 0)
                slate.Set("population", population);
            int lodgerCount = QuestNode_Root_Beggars.LodgerCountFromPopulation(slate, map);
            if (lodgerCount < DeferredRaids.MinPawnsToDefer)
                return false;

            bool beggars = def.defName == Beggars;
            int seed = Rand.Int;
            int childCount = RollChildCount(beggars, lodgerCount, seed);
            var quest = new PendingQuest
            {
                Def = def,
                Map = map,
                Faction = beggars ? NewBeggarFaction() : NewRefugeeFaction(),
                Kind = beggars ? PawnKindDefOf.Beggar : PawnKindDefOf.Refugee,
                LodgerCount = lodgerCount,
                ChildCount = childCount,
                Seed = seed,
                Run = run,
            };
            component.Enqueue(quest);
            if (Prefs.DevMode)
                Log.Message($"[DeferredRaidGeneration] Deferred quest {def.defName}: {lodgerCount} pawns ({childCount} children).");
            Patch_MapPawns_AllPawnsUnspawned.ResetStats();
            return true;
        }

        /// <summary>
        /// The child-count roll of each quest root. The replay runs the root's own roll from the same seed (pushed when
        /// the root asks for the lodger count), which gives the same result as long as nothing else draws random
        /// numbers in between; if it differs anyway, pawns of the other stage are generated normally.
        /// </summary>
        private static int RollChildCount(bool beggars, int lodgerCount, int seed)
        {
            if (!Find.Storyteller.difficulty.ChildrenAllowed || !beggars && lodgerCount < 2)
                return 0;
            Rand.PushState(seed);
            try
            {
                (int, float) result;
                if (beggars)
                {
                    new List<(int, float)>
                    {
                        (0, 0.4f),
                        (Rand.Range(1, Mathf.Max(1, lodgerCount / 2)), 0.4f),
                        (lodgerCount, 0.2f)
                    }.TryRandomElementByWeight(((int, float) p) => p.Item2, out result);
                }
                else
                {
                    new List<(int, float)>
                    {
                        (0, 0.7f),
                        (Rand.Range(1, lodgerCount / 2), 0.2f),
                        (lodgerCount - 1, 0.1f)
                    }.TryRandomElementByWeight(((int, float) p) => p.Item2, out result);
                }
                return result.Item1;
            }
            finally
            {
                Rand.PopState();
            }
        }

        private static List<FactionRelation> NeutralRelations(FactionDef def)
        {
            var list = new List<FactionRelation>();
            foreach (Faction item in Find.FactionManager.AllFactionsListForReading)
            {
                if (!item.def.PermanentlyHostileTo(def))
                    list.Add(new FactionRelation { other = item, kind = FactionRelationKind.Neutral });
            }
            return list;
        }

        private static Faction NewBeggarFaction()
        {
            Faction faction = FactionGenerator.NewGeneratedFactionWithRelations(FactionDefOf.Beggars, NeutralRelations(FactionDefOf.Beggars), hidden: true);
            faction.temporary = true;
            Find.FactionManager.Add(faction);
            return faction;
        }

        private static Faction NewRefugeeFaction()
        {
            FactionDef def = FactionDefOf.OutlanderRefugee;
            bool? hidden = true;
            var parms = new FactionGeneratorParms(def, default(IdeoGenerationParms), hidden);
            if (ModsConfig.IdeologyActive)
                parms.ideoGenerationParms = new IdeoGenerationParms(parms.factionDef, forceNoExpansionIdeo: false,
                    DefDatabase<PreceptDef>.AllDefs.Where(p => p.proselytizes || p.approvesOfCharity).ToList());
            Faction faction = FactionGenerator.NewGeneratedFactionWithRelations(parms, NeutralRelations(def));
            faction.temporary = true;
            Find.FactionManager.Add(faction);
            return faction;
        }
    }

    /// <summary>Storyteller quests (GiveQuest_Beggars, random quests) are deferred here and replayed through the same call.</summary>
    [HarmonyPatchCategory(Features.QuestDeferral)]
    [HarmonyPatch(typeof(IncidentWorker_GiveQuest), "GiveQuest")]
    public static class Patch_IncidentWorker_GiveQuest_GiveQuest
    {
        private static readonly MethodInfo GiveQuest = AccessTools.Method(typeof(IncidentWorker_GiveQuest), "GiveQuest");

        public static bool Prefix(IncidentWorker_GiveQuest __instance, IncidentParms parms, QuestScriptDef questDef)
        {
            if (!DeferredQuests.Supported(questDef) || DeferredRaids.AnyReplaying)
                return true;
            try
            {
                Map map = QuestGen_Get.GetMap();
                return !DeferredQuests.TryDefer(questDef, map, 0, () => GiveQuest.Invoke(__instance, new object[] { parms, questDef }));
            }
            catch (Exception e)
            {
                Log.Error("[DeferredRaidGeneration] Could not defer quest, generating it normally: " + e);
                return true;
            }
        }
    }

    /// <summary>During a replay the root gets the planned lodger count, and the planned seed for its child roll.</summary>
    [HarmonyPatchCategory(Features.QuestDeferral)]
    [HarmonyPatch(typeof(QuestNode_Root_Beggars), nameof(QuestNode_Root_Beggars.LodgerCountFromPopulation))]
    public static class Patch_QuestNode_Root_Beggars_LodgerCountFromPopulation
    {
        public static bool Prefix(ref int __result)
        {
            PendingQuest quest = DeferredQuests.Replaying;
            if (quest == null || !QuestGen.Working)
                return true;
            __result = quest.LodgerCount;
            if (!quest.RandPushed)
            {
                Rand.PushState(quest.Seed);
                quest.RandPushed = true;
            }
            return false;
        }
    }

    /// <summary>During a replay the root gets the faction created when the quest was planned.</summary>
    [HarmonyPatchCategory(Features.QuestDeferral)]
    [HarmonyPatch(typeof(FactionGenerator), nameof(FactionGenerator.NewGeneratedFactionWithRelations),
        typeof(PlanetLayer), typeof(FactionGeneratorParms), typeof(List<FactionRelation>))]
    public static class Patch_FactionGenerator_NewGeneratedFactionWithRelations
    {
        public static bool Prefix(FactionGeneratorParms parms, ref Faction __result)
        {
            PendingQuest quest = DeferredQuests.Replaying;
            if (quest == null || quest.FactionHandedOver || parms.factionDef != quest.Faction.def)
                return true;
            quest.FactionHandedOver = true;
            __result = quest.Faction;
            return false;
        }
    }

    /// <summary>During a replay the quest goes to the map it was planned for.</summary>
    [HarmonyPatchCategory(Features.QuestDeferral)]
    [HarmonyPatch(typeof(QuestGen_Get), nameof(QuestGen_Get.GetMap))]
    public static class Patch_QuestGen_Get_GetMap
    {
        public static bool Prefix(ref Map __result)
        {
            PendingQuest quest = DeferredQuests.Replaying;
            if (quest == null || !Find.Maps.Contains(quest.Map))
                return true;
            __result = quest.Map;
            return false;
        }
    }

    /// <summary>During a replay the root's pawn requests take the matching pre-generated pawns.</summary>
    [HarmonyPatchCategory(Features.QuestDeferral)]
    [HarmonyPatch(typeof(PawnGenerator), nameof(PawnGenerator.GeneratePawn), typeof(PawnGenerationRequest))]
    public static class Patch_PawnGenerator_GeneratePawn_QuestReplay
    {
        [HarmonyPriority(Priority.First)]
        public static bool Prefix(PawnGenerationRequest request, ref Pawn __result)
        {
            PendingQuest quest = DeferredQuests.Replaying;
            if (quest == null)
                return true;
            // The child roll is done once the root starts generating its pawns.
            if (quest.RandPushed)
            {
                Rand.PopState();
                quest.RandPushed = false;
            }
            if (request.KindDef != quest.Kind || request.Faction != quest.Faction)
                return true;
            int index = quest.Generated.FindIndex(p => !p.Destroyed && request.AllowedDevelopmentalStages.Has(p.DevelopmentalStage));
            if (index < 0)
                return true;
            __result = quest.Generated[index];
            quest.Generated.RemoveAt(index);
            quest.HandedOver++;
            return false;
        }
    }

    /// <summary>
    /// A group of pawns that joins the player when its quest is accepted (refugees). Vanilla makes every pawn join
    /// the player's faction and spawns them all in the accept frame; here the first pawn does so at once (so the
    /// letter and quest proceed as usual) and the others join and walk in one per frame, still non-player until then.
    /// </summary>
    public class StaggeredArrival
    {
        public readonly List<Pawn> Waiting = new List<Pawn>();
        /// <summary>Pawns whose SetFaction call to the player was held back.</summary>
        public readonly HashSet<Pawn> FactionHeld = new HashSet<Pawn>();
        public HashSet<Pawn> Group;
        public List<Pawn> DiedThoughtHolders;
        public List<Pawn> QuestPawns;
        public Map Map;
        public IntVec3 SpawnCenter;
        public Rot4 SpawnRotation;
        public bool Queued;
        public int Arrived;
        public float StartTime = Time.realtimeSinceStartup;
    }

    public static class StaggeredArrivals
    {
        /// <summary>Set while QuestPart_PawnsArrive runs for a group that will arrive one pawn per frame.</summary>
        public static StaggeredArrival Current;

        private static readonly List<StaggeredArrival> queue = new List<StaggeredArrival>();

        public static bool HasPending => queue.Count > 0;

        public static void Clear()
        {
            Current = null;
            queue.Clear();
        }

        /// <summary>Called from QuestPart_PawnsArrive.Notify_QuestSignalReceived for a group joining the player.</summary>
        public static void Begin(QuestPart_PawnsArrive part)
        {
            if (!Features.StaggeredJoinActive)
                return;
            PawnsArrivalModeDef mode = part.arrivalMode ?? PawnsArrivalModeDefOf.EdgeWalkIn;
            if (!part.joinPlayer || mode.Worker.GetType() != typeof(PawnsArrivalModeWorker_EdgeWalkIn))
                return;
            var arrival = new StaggeredArrival { Group = DeferredRaids.ReplayPawns, QuestPawns = part.pawns };
            bool first = true;
            foreach (Pawn pawn in part.pawns)
            {
                if (pawn.Destroyed)
                    continue;
                if (first)
                    first = false;
                else
                    arrival.Waiting.Add(pawn);
            }
            if (arrival.Waiting.Count > 0)
                Current = arrival;
        }

        /// <summary>Queues the held pawns, or lets them join now if vanilla never reached the arrival.</summary>
        public static void End()
        {
            StaggeredArrival arrival = Current;
            Current = null;
            if (arrival == null)
                return;
            if (arrival.Queued)
            {
                arrival.DiedThoughtHolders = DeferredRaids.DiedThoughtHolders;
                queue.Add(arrival);
                return;
            }
            foreach (Pawn pawn in arrival.FactionHeld)
            {
                if (!pawn.Destroyed && pawn.Faction != Faction.OfPlayer)
                    pawn.SetFaction(Faction.OfPlayer);
            }
        }

        /// <summary>Lets the next waiting pawn join and walk in. Returns false when nothing is waiting.</summary>
        public static bool Step()
        {
            if (queue.Count == 0)
                return false;
            StaggeredArrival arrival = queue[0];
            if (arrival.Waiting.Count == 0)
            {
                queue.RemoveAt(0);
                if (Prefs.DevMode)
                    Log.Message($"[DeferredRaidGeneration] {arrival.Arrived + 1} quest pawns joined over {Time.realtimeSinceStartup - arrival.StartTime:F1} s.");
                return queue.Count > 0;
            }
            Pawn pawn = arrival.Waiting[0];
            arrival.Waiting.RemoveAt(0);
            DeferredRaids.Staggered.Clear();
            DeferredRaids.ReplayPawns = arrival.Group;
            DeferredRaids.DiedThoughtHolders = arrival.DiedThoughtHolders;
            try
            {
                Arrive(arrival, pawn);
            }
            catch (Exception e)
            {
                Log.Error($"[DeferredRaidGeneration] Staggered arrival of {pawn} failed: " + e);
            }
            finally
            {
                // Jobs ended while joining were not followed by a new search; give those pawns a short wait instead.
                DeferredRaids.StartStaggeredWaits();
                DeferredRaids.Staggered.Clear();
                arrival.DiedThoughtHolders = DeferredRaids.DiedThoughtHolders;
                DeferredRaids.ReplayPawns = null;
                DeferredRaids.DiedThoughtHolders = null;
            }
            return true;
        }

        /// <summary>What vanilla does for this pawn in the accept frame: join, then walk in near the spawn center.</summary>
        private static void Arrive(StaggeredArrival arrival, Pawn pawn)
        {
            if (pawn.Destroyed || pawn.Spawned)
                return;
            // A pawn that died, left the quest or lost its map meanwhile stays as it is.
            if (pawn.Dead || !Find.Maps.Contains(arrival.Map) || !arrival.QuestPawns.Contains(pawn))
                return;
            if (arrival.FactionHeld.Contains(pawn) && pawn.Faction != Faction.OfPlayer)
                pawn.SetFaction(Faction.OfPlayer);
            IntVec3 loc = CellFinder.RandomClosewalkCellNear(arrival.SpawnCenter, arrival.Map, 8);
            GenSpawn.Spawn(pawn, loc, arrival.Map, arrival.SpawnRotation);
            arrival.Arrived++;
            if (pawn.jobs != null && pawn.jobs.curJob == null)
            {
                Job wait = JobMaker.MakeJob(JobDefOf.Wait);
                wait.expiryInterval = Rand.RangeInclusive(1, 30);
                pawn.jobs.StartJob(wait);
            }
        }

        /// <summary>Lets everyone still waiting arrive now (used before saving).</summary>
        public static void FlushAll()
        {
            while (queue.Count > 0)
            {
                StaggeredArrival arrival = queue[0];
                while (arrival.Waiting.Count > 0)
                    Step();
                queue.Remove(arrival);
            }
        }
    }

    /// <summary>
    /// A quest group that arrives later (refugees arrive when the quest is accepted) gets the same arrival treatment
    /// as a replayed group: the died-thoughts shortcut while spawning, and first job searches spread over a few ticks.
    /// A group joining the player also arrives one pawn per frame (StaggeredArrivals).
    /// </summary>
    [HarmonyPatchCategory(Features.ArrivalSmoothing)]
    [HarmonyPatch(typeof(QuestPart_PawnsArrive), nameof(QuestPart_PawnsArrive.Notify_QuestSignalReceived))]
    public static class Patch_QuestPart_PawnsArrive_Group
    {
        [HarmonyPriority(Priority.First)]
        public static void Prefix(QuestPart_PawnsArrive __instance, Signal signal, out bool __state)
        {
            __state = !DeferredRaids.Disabled && DeferredRaids.ReplayPawns == null && signal.tag == __instance.inSignal
                && __instance.pawns.Count >= DeferredRaids.MinPawnsToDefer;
            if (!__state)
                return;
            DeferredRaids.ReplayPawns = new HashSet<Pawn>(__instance.pawns);
            DeferredRaids.DiedThoughtHolders = null;
            DeferredRaids.Staggered.Clear();
            StaggeredArrivals.Begin(__instance);
        }

        public static Exception Finalizer(Exception __exception, QuestPart_PawnsArrive __instance, bool __state)
        {
            if (!__state)
                return __exception;
            try
            {
                StaggeredArrivals.End();
                // Arriving pawns without a lord pick their first job on their first tick, all in the same tick.
                foreach (Pawn pawn in __instance.pawns)
                {
                    if (!DeferredRaids.Staggered.Contains(pawn))
                        DeferredRaids.Staggered.Add(pawn);
                }
                DeferredRaids.StartStaggeredWaits();
            }
            finally
            {
                StaggeredArrivals.Current = null;
                DeferredRaids.ReplayPawns = null;
                DeferredRaids.DiedThoughtHolders = null;
                DeferredRaids.Staggered.Clear();
            }
            return __exception;
        }
    }

    /// <summary>Holds back joining the player for the pawns of a staggered arrival other than the first.</summary>
    [HarmonyPatchCategory(Features.StaggeredJoin)]
    [HarmonyPatch(typeof(Pawn), nameof(Pawn.SetFaction))]
    public static class Patch_Pawn_SetFaction_StaggeredArrival
    {
        [HarmonyPriority(Priority.First)]
        public static bool Prefix(Pawn __instance, Faction newFaction)
        {
            StaggeredArrival arrival = StaggeredArrivals.Current;
            if (arrival == null || arrival.Queued || newFaction != Faction.OfPlayer || !arrival.Waiting.Contains(__instance))
                return true;
            arrival.FactionHeld.Add(__instance);
            return false;
        }
    }

    /// <summary>Spawns only the first pawn of a staggered arrival and remembers where the others walk in.</summary>
    [HarmonyPatchCategory(Features.StaggeredJoin)]
    [HarmonyPatch(typeof(PawnsArrivalModeWorker_EdgeWalkIn), nameof(PawnsArrivalModeWorker_EdgeWalkIn.Arrive))]
    public static class Patch_PawnsArrivalModeWorker_EdgeWalkIn_Arrive
    {
        [HarmonyPriority(Priority.First)]
        public static bool Prefix(List<Pawn> pawns, IncidentParms parms)
        {
            StaggeredArrival arrival = StaggeredArrivals.Current;
            if (arrival == null || arrival.Queued || pawns != arrival.QuestPawns || !(parms.target is Map map))
                return true;
            arrival.Map = map;
            arrival.SpawnCenter = parms.spawnCenter;
            arrival.SpawnRotation = parms.spawnRotation;
            arrival.Queued = true;
            foreach (Pawn pawn in pawns)
            {
                if (arrival.Waiting.Contains(pawn))
                    continue;
                IntVec3 loc = CellFinder.RandomClosewalkCellNear(parms.spawnCenter, map, 8);
                GenSpawn.Spawn(pawn, loc, map, parms.spawnRotation);
            }
            return false;
        }
    }
}
